-- 코드를 작성해주세요
# SELECT * FROM ITEM_TREE IT
# LEFT JOIN ITEM_INFO II ON IT.PARENT_ITEM_ID = II.ITEM_ID;



SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO
WHERE ITEM_ID IN
(SELECT II.ITEM_ID FROM ITEM_INFO II
LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NULL)
ORDER BY ITEM_ID DESC;